# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mva', '0002_auto_20160328_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('a', 'Approved'), ('s', 'Submited'), ('r', 'Rejected')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
