# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mva', '0004_session_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 7, 3, 3, 10, 43, 599887, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='salon',
            field=models.CharField(blank=True, choices=[('Salón Jupiter', 'Salón Jupiter'), ('Salón Marte', 'Salón Marte'), ('Salón Tierra', 'Salón Tierra'), ('Salón Venus', 'Salón Venus')], max_length=20),
        ),
    ]
