# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 03:17
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('mva', '0005_auto_20160703_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='abstract',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
