# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 03:46
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mva', '0006_auto_20160703_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='abstract',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
