# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mva', '0007_auto_20160703_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='abstract',
            field=models.TextField(max_length=1000),
        ),
    ]
