# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mva', '0009_auto_20160703_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='people_max',
        ),
        migrations.AddField(
            model_name='session',
            name='places',
            field=models.PositiveSmallIntegerField(default=200),
        ),
    ]
