# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mva', '0011_auto_20160703_0629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set([('session', 'person')]),
        ),
    ]
